from datetime import datetime, timedelta


TODAY = datetime.today()
CURRENT_MONTH_START = datetime(TODAY.year, TODAY.month, 1)
LAST_YEAR = TODAY - timedelta(days=365)
LAST_60_DAYS = TODAY - timedelta(days=60)


EXTRA_PROPIETARIOS = [
    {
        "id_propietario": "PRA001",
        "nombre": "Lucia",
        "apellido": "Benitez",
        "dni": "40111222",
        "email": "lucia.benitez@email.com",
        "telefono": "1122334455",
        "ciudad": "CABA",
        "provincia": "Buenos Aires",
        "activo": True,
    },
    {
        "id_propietario": "PRA002",
        "nombre": "Martin",
        "apellido": "Arias",
        "dni": "38999888",
        "email": "martin.arias@email.com",
        "telefono": "1133445566",
        "ciudad": "San Isidro",
        "provincia": "Buenos Aires",
        "activo": True,
    },
    {
        "id_propietario": "PRA003",
        "nombre": "Carolina",
        "apellido": "Mendez",
        "dni": "37123456",
        "email": "carolina.mendez@email.com",
        "telefono": "1144556677",
        "ciudad": "Tigre",
        "provincia": "Buenos Aires",
        "activo": True,
    },
    {
        "id_propietario": "PRA004",
        "nombre": "Diego",
        "apellido": "Romero",
        "dni": "35666777",
        "email": "diego.romero@email.com",
        "telefono": "1155667788",
        "ciudad": "La Plata",
        "provincia": "Buenos Aires",
        "activo": True,
    },
    {
        "id_propietario": "PRA005",
        "nombre": "Paula",
        "apellido": "Suarez",
        "dni": "34987654",
        "email": "paula.suarez@email.com",
        "telefono": "1166778899",
        "ciudad": "CABA",
        "provincia": "Buenos Aires",
        "activo": True,
    },
    {
        "id_propietario": "PRA006",
        "nombre": "Federico",
        "apellido": "Lopez",
        "dni": "33111222",
        "email": "federico.lopez@email.com",
        "telefono": "1177889900",
        "ciudad": "Moron",
        "provincia": "Buenos Aires",
        "activo": True,
    },
    {
        "id_propietario": "PRA007",
        "nombre": "Sofia",
        "apellido": "Nuñez",
        "dni": "32777111",
        "email": "sofia.nunez@email.com",
        "telefono": "1188990011",
        "ciudad": "CABA",
        "provincia": "Buenos Aires",
        "activo": True,
    },
    {
        "id_propietario": "PRA008",
        "nombre": "Andres",
        "apellido": "Rivas",
        "dni": "31555444",
        "email": "andres.rivas@email.com",
        "telefono": "1199001122",
        "ciudad": "Quilmes",
        "provincia": "Buenos Aires",
        "activo": True,
    },
    {
        "id_propietario": "PRA009",
        "nombre": "Valentina",
        "apellido": "Castro",
        "dni": "30999111",
        "email": "valentina.castro@email.com",
        "telefono": "1100112233",
        "ciudad": "CABA",
        "provincia": "Buenos Aires",
        "activo": True,
    },
    {
        "id_propietario": "PRA010",
        "nombre": "Nicolas",
        "apellido": "Ferreyra",
        "dni": "29888777",
        "email": "nicolas.ferreyra@email.com",
        "telefono": "1111223344",
        "ciudad": "Vicente Lopez",
        "provincia": "Buenos Aires",
        "activo": True,
    },
]


EXTRA_VETERINARIOS = [
    {
        "id_vet": "VEX001",
        "nombre": "Ana",
        "apellido": "Pereyra",
        "matricula": "MN9001",
        "especialidad": "Clinica general",
        "sucursal": "Palermo",
        "activo": True,
    },
    {
        "id_vet": "VEX002",
        "nombre": "Bruno",
        "apellido": "Salvatierra",
        "matricula": "MN9002",
        "especialidad": "Dermatologia",
        "sucursal": "Belgrano",
        "activo": True,
    },
    {
        "id_vet": "VEX003",
        "nombre": "Camila",
        "apellido": "Ojeda",
        "matricula": "MN9003",
        "especialidad": "Cardiologia",
        "sucursal": "Palermo",
        "activo": True,
    },
    {
        "id_vet": "VEX004",
        "nombre": "Esteban",
        "apellido": "Molina",
        "matricula": "MN9004",
        "especialidad": "Cirugia",
        "sucursal": "Recoleta",
        "activo": True,
    },
    {
        "id_vet": "VEX005",
        "nombre": "Julieta",
        "apellido": "Campos",
        "matricula": "MN9005",
        "especialidad": "Vacunacion",
        "sucursal": "Caballito",
        "activo": True,
    },
    {
        "id_vet": "VEX006",
        "nombre": "Tomas",
        "apellido": "Ibarra",
        "matricula": "MN9006",
        "especialidad": "Clinica general",
        "sucursal": "Belgrano",
        "activo": True,
    },
    {
        "id_vet": "VEX007",
        "nombre": "Marina",
        "apellido": "Sosa",
        "matricula": "MN9007",
        "especialidad": "Traumatologia",
        "sucursal": "Recoleta",
        "activo": True,
    },
    {
        "id_vet": "VEX008",
        "nombre": "Ramiro",
        "apellido": "Acosta",
        "matricula": "MN9008",
        "especialidad": "Clinica general",
        "sucursal": "Palermo",
        "activo": False,
    },
    {
        "id_vet": "VEX009",
        "nombre": "Agustina",
        "apellido": "Luna",
        "matricula": "MN9009",
        "especialidad": "Dermatologia",
        "sucursal": "Caballito",
        "activo": True,
    },
    {
        "id_vet": "VEX010",
        "nombre": "Pedro",
        "apellido": "Vera",
        "matricula": "MN9010",
        "especialidad": "Neurologia",
        "sucursal": "Belgrano",
        "activo": True,
    },
]


EXTRA_PACIENTES = [
    {
        "id_paciente": "PEX001",
        "nombre": "Mora",
        "especie": "Perro",
        "raza": "Labrador",
        "fecha_nac": datetime(2019, 5, 14),
        "id_propietario": "PRA001",
        "activo": True,
    },
    {
        "id_paciente": "PEX002",
        "nombre": "Tango",
        "especie": "Perro",
        "raza": "Caniche",
        "fecha_nac": datetime(2021, 3, 20),
        "id_propietario": "PRA001",
        "activo": True,
    },
    {
        "id_paciente": "PEX003",
        "nombre": "Luna",
        "especie": "Gato",
        "raza": "Siames",
        "fecha_nac": datetime(2020, 8, 9),
        "id_propietario": "PRA002",
        "activo": True,
    },
    {
        "id_paciente": "PEX004",
        "nombre": "Roco",
        "especie": "Perro",
        "raza": "Bulldog",
        "fecha_nac": datetime(2018, 11, 2),
        "id_propietario": "PRA003",
        "activo": True,
    },
    {
        "id_paciente": "PEX005",
        "nombre": "Nina",
        "especie": "Gato",
        "raza": "Europeo comun",
        "fecha_nac": datetime(2022, 1, 12),
        "id_propietario": "PRA003",
        "activo": True,
    },
    {
        "id_paciente": "PEX006",
        "nombre": "Coco",
        "especie": "Conejo",
        "raza": "Mini lop",
        "fecha_nac": datetime(2021, 7, 7),
        "id_propietario": "PRA004",
        "activo": True,
    },
    {
        "id_paciente": "PEX007",
        "nombre": "Simba",
        "especie": "Gato",
        "raza": "Maine Coon",
        "fecha_nac": datetime(2017, 4, 1),
        "id_propietario": "PRA005",
        "activo": True,
    },
    {
        "id_paciente": "PEX008",
        "nombre": "India",
        "especie": "Perro",
        "raza": "Border Collie",
        "fecha_nac": datetime(2020, 10, 18),
        "id_propietario": "PRA006",
        "activo": True,
    },
    {
        "id_paciente": "PEX009",
        "nombre": "Olivia",
        "especie": "Perro",
        "raza": "Golden Retriever",
        "fecha_nac": datetime(2016, 6, 23),
        "id_propietario": "PRA007",
        "activo": False,
    },
    {
        "id_paciente": "PEX010",
        "nombre": "Felix",
        "especie": "Gato",
        "raza": "Persa",
        "fecha_nac": datetime(2019, 9, 30),
        "id_propietario": "PRA008",
        "activo": True,
    },
]


EXTRA_CONSULTAS = [
    {
        "id_consulta": "CEX001",
        "id_paciente": "PEX001",
        "id_vet": "VEX001",
        "fecha": TODAY - timedelta(days=10),
        "motivo": "Control general",
        "tipo_consulta": "Control",
        "diagnostico": "Sano",
        "costo": 4200.0,
        "estado": "Cerrada",
    },
    {
        "id_consulta": "CEX002",
        "id_paciente": "PEX002",
        "id_vet": "VEX002",
        "fecha": TODAY - timedelta(days=8),
        "motivo": "Picazon persistente",
        "tipo_consulta": "Otra",
        "diagnostico": "Dermatitis",
        "costo": 7600.0,
        "estado": "Seguimiento",
    },
    {
        "id_consulta": "CEX003",
        "id_paciente": "PEX003",
        "id_vet": "VEX003",
        "fecha": TODAY - timedelta(days=6),
        "motivo": "Control cardiologico",
        "tipo_consulta": "Control",
        "diagnostico": "Soplo leve",
        "costo": 4900.0,
        "estado": "Seguimiento",
    },
    {
        "id_consulta": "CEX004",
        "id_paciente": "PEX004",
        "id_vet": "VEX004",
        "fecha": CURRENT_MONTH_START + timedelta(days=2),
        "motivo": "Dolor abdominal",
        "tipo_consulta": "Otra",
        "diagnostico": "Gastritis",
        "costo": 8800.0,
        "estado": "Cerrada",
    },
    {
        "id_consulta": "CEX005",
        "id_paciente": "PEX005",
        "id_vet": "VEX005",
        "fecha": CURRENT_MONTH_START + timedelta(days=3),
        "motivo": "Control post vacuna",
        "tipo_consulta": "Control",
        "diagnostico": "Sano",
        "costo": 3900.0,
        "estado": "Cerrada",
    },
    {
        "id_consulta": "CEX006",
        "id_paciente": "PEX006",
        "id_vet": "VEX006",
        "fecha": TODAY - timedelta(days=30),
        "motivo": "Diarrea",
        "tipo_consulta": "Otra",
        "diagnostico": "Gastritis",
        "costo": 6500.0,
        "estado": "Seguimiento",
    },
    {
        "id_consulta": "CEX007",
        "id_paciente": "PEX007",
        "id_vet": "VEX007",
        "fecha": TODAY - timedelta(days=45),
        "motivo": "Cojera",
        "tipo_consulta": "Otra",
        "diagnostico": "Esguince",
        "costo": 9200.0,
        "estado": "Cerrada",
    },
    {
        "id_consulta": "CEX008",
        "id_paciente": "PEX008",
        "id_vet": "VEX001",
        "fecha": TODAY - timedelta(days=400),
        "motivo": "Control anual",
        "tipo_consulta": "Control",
        "diagnostico": "Sano",
        "costo": 3600.0,
        "estado": "Cerrada",
    },
    {
        "id_consulta": "CEX009",
        "id_paciente": "PEX010",
        "id_vet": "VEX009",
        "fecha": TODAY - timedelta(days=20),
        "motivo": "Lesion en piel",
        "tipo_consulta": "Otra",
        "diagnostico": "Dermatitis",
        "costo": 7300.0,
        "estado": "Seguimiento",
    },
    {
        "id_consulta": "CEX010",
        "id_paciente": "PEX001",
        "id_vet": "VEX010",
        "fecha": CURRENT_MONTH_START + timedelta(days=5),
        "motivo": "Control neurologico",
        "tipo_consulta": "Control",
        "diagnostico": "Sano",
        "costo": 4700.0,
        "estado": "Cerrada",
    },
]


EXTRA_VACUNACIONES = [
    {
        "id_vacuna": "VAX001",
        "id_paciente": "PEX001",
        "id_vet": "VEX005",
        "fecha_aplicacion": TODAY - timedelta(days=400),
        "nombre_vacuna": "Antirrabica",
        "proxima_dosis": TODAY - timedelta(days=30),
    },
    {
        "id_vacuna": "VAX002",
        "id_paciente": "PEX002",
        "id_vet": "VEX005",
        "fecha_aplicacion": TODAY - timedelta(days=200),
        "nombre_vacuna": "Quintuple",
        "proxima_dosis": TODAY + timedelta(days=160),
    },
    {
        "id_vacuna": "VAX003",
        "id_paciente": "PEX003",
        "id_vet": "VEX005",
        "fecha_aplicacion": TODAY - timedelta(days=500),
        "nombre_vacuna": "Triple felina",
        "proxima_dosis": TODAY - timedelta(days=120),
    },
    {
        "id_vacuna": "VAX004",
        "id_paciente": "PEX004",
        "id_vet": "VEX005",
        "fecha_aplicacion": TODAY - timedelta(days=100),
        "nombre_vacuna": "Antirrabica",
        "proxima_dosis": TODAY + timedelta(days=260),
    },
    {
        "id_vacuna": "VAX005",
        "id_paciente": "PEX005",
        "id_vet": "VEX005",
        "fecha_aplicacion": TODAY - timedelta(days=370),
        "nombre_vacuna": "Triple felina",
        "proxima_dosis": TODAY - timedelta(days=5),
    },
    {
        "id_vacuna": "VAX006",
        "id_paciente": "PEX006",
        "id_vet": "VEX005",
        "fecha_aplicacion": TODAY - timedelta(days=50),
        "nombre_vacuna": "Mixomatosis",
        "proxima_dosis": TODAY + timedelta(days=310),
    },
    {
        "id_vacuna": "VAX007",
        "id_paciente": "PEX007",
        "id_vet": "VEX005",
        "fecha_aplicacion": TODAY - timedelta(days=430),
        "nombre_vacuna": "Antirrabica",
        "proxima_dosis": TODAY - timedelta(days=60),
    },
    {
        "id_vacuna": "VAX008",
        "id_paciente": "PEX008",
        "id_vet": "VEX005",
        "fecha_aplicacion": TODAY - timedelta(days=20),
        "nombre_vacuna": "Quintuple",
        "proxima_dosis": TODAY + timedelta(days=345),
    },
    {
        "id_vacuna": "VAX009",
        "id_paciente": "PEX009",
        "id_vet": "VEX005",
        "fecha_aplicacion": TODAY - timedelta(days=600),
        "nombre_vacuna": "Antirrabica",
        "proxima_dosis": TODAY - timedelta(days=240),
    },
    {
        "id_vacuna": "VAX010",
        "id_paciente": "PEX010",
        "id_vet": "VEX005",
        "fecha_aplicacion": TODAY - timedelta(days=90),
        "nombre_vacuna": "Triple felina",
        "proxima_dosis": TODAY + timedelta(days=270),
    },
]


EXTRA_CIRUGIAS = [
    {
        "id_cirugia": "CIR001",
        "id_paciente": "PEX004",
        "id_vet": "VEX004",
        "fecha": TODAY - timedelta(days=70),
        "tipo": "Extraccion dental",
        "resultado": "Exitosa",
        "costo": 22000.0,
    },
    {
        "id_cirugia": "CIR002",
        "id_paciente": "PEX007",
        "id_vet": "VEX007",
        "fecha": TODAY - timedelta(days=120),
        "tipo": "Sutura de herida",
        "resultado": "Exitosa",
        "costo": 18000.0,
    },
    {
        "id_cirugia": "CIR003",
        "id_paciente": "PEX001",
        "id_vet": "VEX004",
        "fecha": TODAY - timedelta(days=200),
        "tipo": "Castracion",
        "resultado": "Exitosa",
        "costo": 25000.0,
    },
    {
        "id_cirugia": "CIR004",
        "id_paciente": "PEX002",
        "id_vet": "VEX004",
        "fecha": TODAY - timedelta(days=300),
        "tipo": "Limpieza dental",
        "resultado": "Exitosa",
        "costo": 16000.0,
    },
    {
        "id_cirugia": "CIR005",
        "id_paciente": "PEX003",
        "id_vet": "VEX004",
        "fecha": TODAY - timedelta(days=20),
        "tipo": "Biopsia",
        "resultado": "Pendiente",
        "costo": 30000.0,
    },
    {
        "id_cirugia": "CIR006",
        "id_paciente": "PEX005",
        "id_vet": "VEX004",
        "fecha": TODAY - timedelta(days=95),
        "tipo": "Extraccion dental",
        "resultado": "Exitosa",
        "costo": 21000.0,
    },
    {
        "id_cirugia": "CIR007",
        "id_paciente": "PEX006",
        "id_vet": "VEX007",
        "fecha": TODAY - timedelta(days=160),
        "tipo": "Correccion traumatologica",
        "resultado": "Exitosa",
        "costo": 42000.0,
    },
    {
        "id_cirugia": "CIR008",
        "id_paciente": "PEX008",
        "id_vet": "VEX004",
        "fecha": TODAY - timedelta(days=12),
        "tipo": "Castracion",
        "resultado": "Exitosa",
        "costo": 26000.0,
    },
    {
        "id_cirugia": "CIR009",
        "id_paciente": "PEX010",
        "id_vet": "VEX007",
        "fecha": TODAY - timedelta(days=44),
        "tipo": "Sutura de herida",
        "resultado": "Exitosa",
        "costo": 17500.0,
    },
    {
        "id_cirugia": "CIR010",
        "id_paciente": "PEX001",
        "id_vet": "VEX004",
        "fecha": TODAY - timedelta(days=5),
        "tipo": "Extraccion de cuerpo extraño",
        "resultado": "Exitosa",
        "costo": 38000.0,
    },
]


EXTRA_STOCK = [
    {
        "id_producto": "PRX001",
        "nombre": "Antibiotico canino",
        "categoria": "Medicamento",
        "unidades": 35,
        "precio_unit": 1800.0,
        "vencimiento": "2027-01-15",
        "proveedor": "VetPharma",
    },
    {
        "id_producto": "PRX002",
        "nombre": "Antiinflamatorio felino",
        "categoria": "Medicamento",
        "unidades": 48,
        "precio_unit": 1500.0,
        "vencimiento": "2026-12-10",
        "proveedor": "AnimalCare",
    },
    {
        "id_producto": "PRX003",
        "nombre": "Vacuna antirrabica",
        "categoria": "Vacuna",
        "unidades": 120,
        "precio_unit": 2200.0,
        "vencimiento": "2027-05-01",
        "proveedor": "BioVet",
    },
    {
        "id_producto": "PRX004",
        "nombre": "Suero fisiologico",
        "categoria": "Insumo",
        "unidades": 25,
        "precio_unit": 900.0,
        "vencimiento": "2026-09-20",
        "proveedor": "MedVet",
    },
    {
        "id_producto": "PRX005",
        "nombre": "Gasas esteriles",
        "categoria": "Insumo",
        "unidades": 200,
        "precio_unit": 300.0,
        "vencimiento": "2028-03-15",
        "proveedor": "MedVet",
    },
    {
        "id_producto": "PRX006",
        "nombre": "Anestesico",
        "categoria": "Medicamento",
        "unidades": 15,
        "precio_unit": 5000.0,
        "vencimiento": "2026-11-30",
        "proveedor": "VetSur",
    },
    {
        "id_producto": "PRX007",
        "nombre": "Collar isabelino",
        "categoria": "Accesorio",
        "unidades": 65,
        "precio_unit": 2500.0,
        "vencimiento": "2030-01-01",
        "proveedor": "PetSupply",
    },
    {
        "id_producto": "PRX008",
        "nombre": "Jeringas descartables",
        "categoria": "Insumo",
        "unidades": 42,
        "precio_unit": 120.0,
        "vencimiento": "2028-06-10",
        "proveedor": "MedVet",
    },
    {
        "id_producto": "PRX009",
        "nombre": "Shampoo dermatologico",
        "categoria": "Higiene",
        "unidades": 80,
        "precio_unit": 3200.0,
        "vencimiento": "2027-02-28",
        "proveedor": "AnimalCare",
    },
    {
        "id_producto": "PRX010",
        "nombre": "Alimento gastrointestinal",
        "categoria": "Alimento",
        "unidades": 18,
        "precio_unit": 7500.0,
        "vencimiento": "2026-08-15",
        "proveedor": "NutriPet",
    },
]